// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnNry55FGDJiAhuQvDFWJljFu-yaISpZY',
    appId: '1:868962755815:web:97ce5fdd93eebc9051ae42',
    messagingSenderId: '868962755815',
    projectId: 'greentools-e7d0f',
    authDomain: 'greentools-e7d0f.firebaseapp.com',
    storageBucket: 'greentools-e7d0f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKCyYwwqn355o95sSbf52WG6YfJcKXKjU',
    appId: '1:868962755815:android:03b9fc962121ee9e51ae42',
    messagingSenderId: '868962755815',
    projectId: 'greentools-e7d0f',
    storageBucket: 'greentools-e7d0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJW5px8y9NQeAujT1Tazsnqa886en_CJQ',
    appId: '1:868962755815:ios:9c036490de317ae951ae42',
    messagingSenderId: '868962755815',
    projectId: 'greentools-e7d0f',
    storageBucket: 'greentools-e7d0f.appspot.com',
    iosBundleId: 'com.example.dymatestflutter',
  );
}
